Draft of duckdb support
openjusticeok/ojodb pull request #168
Opened 2024-05-27 04:05 UTC by brancengregory

2024-05-27 04:07 UTC, brancengregory commented
@andrewjbe This can pull all unique counts as filed in a couple seconds. Computes counts of distinct minute codes in seconds, too.

2024-05-27 04:11 UTC, brancengregory commented
In order for us to be able to run queries lazily on multiple remote tables with joins, we will need to use the same db source. That means pulling out the connection creation from `tbl_from_gcs_duckdb` and moving it into `ojo_connect` with a new argument that can be `postgres` or `duckdb`.

2024-05-27 04:12 UTC, brancengregory commented
Also, the values allowed for `ojo_tbl(.source = ` need to be updated to `c("postgres", "gcs_arrow", "gcs_duckdb")`, making sure not to break the current API

2024-05-27 04:13 UTC, brancengregory commented
It would be really great if we could set the `ojo_tbl` source at the global level, perhaps in an env variable or with `options()`

2024-05-27 18:43 UTC, brancengregory commented
@andrewjbe this is ready for ya

2024-06-04 20:13 UTC, andrewjbe commented
The `.source = "duckdb"` argument currently has an issue where it will work if it's the first connection you make in the session: 
![Screenshot from 2024-06-04 15-01-23](https://github.com/openjusticeok/ojodb/assets/56839927/e3f8b754-a86e-40fd-a5d4-35bc52e5657e)

But it will fail if you use `.source = "postgres"` beforehand:
![Screenshot from 2024-06-04 15-00-32](https://github.com/openjusticeok/ojodb/assets/56839927/6cfd33f7-2285-4bb3-9a3b-7ea34dbe254a)

2024-06-04 20:15 UTC, andrewjbe requested changes
Still need to address the bug with connection handling at some point

2024-06-04 20:15 UTC, andrewjbe commented on R/ojo_tbl.R
The only actual change here is that I renamed the args to be 'postgres', 'gcs_duckdb', and 'gcs_parquet'

2024-06-09 19:24 UTC, brancengregory commented
I changed the arrow source argument from `gcs_parquet` to `gcs_arrow`, but left your other changes. I made it to where connection objects are stored independently based on connection type and source so that a connection to postgres and one to duckdb will be handled independently, even coexisting in the same session.

2024-06-10 21:04 UTC, andrewjbe commented
Added the following chunk to `ojo_collect()` so that it will work no matter what connection type you're using:

>     # Check class of `.data`
>     # First, check if it's an arrow connection; this won't work with the rest of ojo_collect()
>   
>     if (inherits(.data, "ArrowTabular")) {
> 
>     # Display CLI
>     cli::cli_div(
>       theme = list(
>         rule = list(color = "br_yellow",
>                     "line-type" = "single"),
>         "span.grayed" = list(color = "grey")
>       )
>     )
> 
>     cli::cli_rule(left = paste("Connection: OJO GCS Arrow Tables"),
>                   right = "{.emph ojodb {utils::packageVersion('ojodb')}}")
> 
>     return(dplyr::collect(.data))
> 
>     }

2024-06-10 22:02 UTC, merged